Repository PlaceOS/core, pull requests merged in 2022-03, with the labels that each got.

#163 fix: better module stopped errors
  .github/workflows/ci.yml
  src/api/command.cr
  src/placeos-core/error.cr
  src/placeos-core/process_manager/local.cr
Labels: type: enhancement, type: refactor

#167 ci: reword TODOS in code, add `todos.yml`
  .github/workflows/todos.yml
  spec/processes/edge_spec.cr
  src/placeos-core/compilation.cr
  src/placeos-core/module_manager.cr
  src/placeos-core/process_manager/edge.cr
  src/placeos-core/process_manager/local.cr
  src/placeos-edge/protocol.cr
Labels: type: documentation, type: maintenance

#170 build: bump `placeos-models`
  shard.lock
  shard.yml
Labels: type: maintenance

#171 fix: possible race condition in spawn
  src/placeos-core.cr
Labels: focus: backend, product: placeos, priority: high

#172 fix(api): add error codes coming from RemoteExceptions
  src/api/command.cr
Labels: focus: backend, product: placeos, squad: core, priority: high, type: bug

#173 chore(shard.lock): bump dependencies
  shard.lock
Labels: focus: backend, product: placeos, priority: high, dependencies
